# Generated by Django 4.0.4 on 2022-05-20 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concerts', '0002_remove_concert_user_concert_user_remove_song_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='user',
        ),
        migrations.AddField(
            model_name='concert',
            name='user',
            field=models.ManyToManyField(null=True, related_name='concerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ManyToManyField(null=True, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
